version: '3'
services:
  db_postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env.docker
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
  app:
    build:
      context: .
      args:
        ENVIRONMENT_NAME: .docker
        BUILD_NAME: docker
    restart: always
    depends_on:
      - db_postgres
      - redis
    ports:
      - 9000:9000
    env_file:
      - ./.env.docker
